// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klvsdmlqcommhwvlnzal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsdnNkbWxxY29tbWh3dmxuemFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMjk1MjAsImV4cCI6MjA2OTYwNTUyMH0.9MgBQo0JBl9ZXmtePQ0k90us-sbH0CT0FCJNRODt5Ig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});